### ISSUE TITLE
During the algorithm initialization, the following exception has occurred: System.ArgumentException: ApiDataProvider(): Must be subscribed to map and factor files to use the ApiDataProvider to download Equity data from QuantConnect, when selecting Interactive Brokers as the brokerage and data feed

### ISSUE THREAD

**Issue by chriscdev** [QuantConnect/lean-cli#124]
Good day,

When running the standard sample algorithm that uses SPY data, using the following:

- Using Lean version 1.0.97
- Run locally using lean live
- Interactive Brokers as brokerage
- Interactive Brokers as data feed and delayed data on

The following error is reported:

20220808 11:50:18.429 ERROR:: During the algorithm initialization, the following exception has occurred: System.ArgumentException:
ApiDataProvider(): Must be subscribed to map and factor files to use the ApiDataProvider to download Equity data from QuantConnect. Please
visit https://www.quantconnect.com/datasets/quantconnect-security-master for details.
   at QuantConnect.Lean.Engine.DataFeeds.ApiDataProvider.NeedToDownload(String filePath) in
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/ApiDataProvider.cs:line 204
   at QuantConnect.Lean.Engine.DataFeeds.BaseDownloaderDataProvider.DownloadOnce(String key, Action`1 download) in
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/BaseDownloaderDataProvider.cs:line 39
   at QuantConnect.Lean.Engine.DataFeeds.ApiDataProvider.Fetch(String key) in
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/ApiDataProvider.cs:line 131
   at QuantConnect.Data.Auxiliary.LocalZipMapFileProvider.GetMapFileResolver(AuxiliaryDataKey auxiliaryDataKey) in
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Data/Auxiliary/LocalZipMapFileProvider.cs:line 112
   at QuantConnect.Data.Auxiliary.LocalZipMapFileProvider.Get(AuxiliaryDataKey auxiliaryDataKey) in
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Data/Auxiliary/LocalZipMapFileProvider.cs:line 78
   at QuantConnect.SecurityIdentifier.GetFirstTickerAndDate(IMapFileProvider mapFileProvider, String tickerToday, String market, SecurityType
securityType, Nullable`1 mappingResolveDate) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/SecurityIdentifier.cs:line 632
   at QuantConnect.SecurityIdentifier.GenerateEquity(String symbol, String market, Boolean mapSymbol, IMapFileProvider mapFileProvider,
Nullable`1 mappingResolveDate) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/SecurityIdentifier.cs:line 421
   at QuantConnect.Symbol.Create(String ticker, SecurityType securityType, String market, String alias, Type baseDataType) in
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Symbol.cs:line 71
   at QuantConnect.Algorithm.QCAlgorithm.AddSecurity[T](SecurityType securityType, String ticker, Nullable`1 resolution, String market,
Boolean fillDataForward, Decimal leverage, Boolean extendedMarketHours, Nullable`1 mappingMode, Nullable`1 normalizationMode) in
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Algorithm/QCAlgorithm.cs:line 2520
   at QuantConnect.Algorithm.QCAlgorithm.AddEquity(String ticker, Nullable`1 resolution, String market, Boolean fillDataForward, Decimal
leverage, Boolean extendedMarketHours, Nullable`1 dataNormalizationMode) in
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Algorithm/QCAlgorithm.cs:line 1723
--- End of stack trace from previous location ---
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.PyObject.Invoke(PyTuple args, PyDict kw)
   at Python.Runtime.PyObject.InvokeMethod(String name, PyTuple args, PyDict kw)
   at Python.Runtime.PyObject.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   at QuantConnect.AlgorithmFactory.Python.Wrappers.AlgorithmPythonWrapper.Initialize() in
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/AlgorithmFactory/Python/Wrappers/AlgorithmPythonWrapper.cs:line 526
   at QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler.<>c__DisplayClass29_0.<Setup>b__1() in
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Setup/BrokerageSetupHandler.cs:line 281ApiDataProvider(): Must be subscribed to
map and factor files to use the ApiDataProvider to download Equity data from QuantConnect. Please visit
https://www.quantconnect.com/datasets/quantconnect-security-master for details. in ApiDataProvider.cs:line 204 ApiDataProvider(): Must be
subscribed to map and factor files to use the ApiDataProvider to download Equity data from QuantConnect. Please visit
https://www.quantconnect.com/datasets/quantconnect-security-master for details.

Looking at other posts this is related to using the data download but in this case no data is requested to download and the data-feed is set to Interactive Brokers. This used to work in previous versions of Lean.

Please see the attached log: 
[log.txt](https://github.com/QuantConnect/lean-cli/files/9281541/log.txt)

Regards,
Chris

**Comment by rjra2611** [comment]
Hey Chris,

You would face this issue because of an incorrect data-provider value in your lean.json. Which is now fixed by https://github.com/QuantConnect/lean-cli/pull/125

To update the data provider value when running `lean live`  you can use `--data-provider`  option as ` lean live --data-provider "data provider here" <project-name>`

You only need to use this option when you intend to update the data provider value. By default, lean will always use the value used in the last run

To check the available data providers you can run `lean live --help` or checkout the lean-cli [readme](https://github.com/QuantConnect/Lean-cli#lean-live)

**Comment by chriscdev** [comment]
Thanks Ronit!
