### ISSUE TITLE
lean fails to download docker image on M1 MacBook

### ISSUE THREAD

**Issue by ben-green-kerro** [QuantConnect/lean-cli#146]
I always get the following error when trying to run a local backtest. lean and docker are updated. any help is appreciated.

> Pulling lean-cli/engine:formac...
Error response from daemon: pull access denied for lean-cli/engine, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error: Something went wrong while pulling lean-cli/engine:formac, see the logs above for more information

here it is with verbose mode turned on

> Pulling lean-cli/engine:formac...
Error response from daemon: pull access denied for lean-cli/engine, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/lean/main.py", line 103, in main
    lean.main(standalone_mode=False)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.10/site-packages/lean/click.py", line 125, in invoke
    result = super().invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/lean/commands/backtest.py", line 343, in backtest
    container.update_manager().pull_docker_image_if_necessary(engine_image, update)
  File "/opt/homebrew/lib/python3.10/site-packages/lean/components/util/update_manager.py", line 115, in pull_docker_image_if_necessary
    self._docker_manager.pull_image(image)
  File "/opt/homebrew/lib/python3.10/site-packages/lean/components/docker/docker_manager.py", line 70, in pull_image
    raise RuntimeError(
RuntimeError: Something went wrong while pulling lean-cli/engine:formac, see the logs above for more information
Error: Something went wrong while pulling lean-cli/engine:formac, see the logs above for more information

**Comment by ben-green-kerro** [comment]
All I am doing is following the first example copied below:

`lean init
lean create-project “My Project”
lean backtest “My Project”`

The error I get invariably looks like this

`Skip pulling local image lean-cli/engine:formac...
Skip pulling local image lean-cli/engine:formac...
Error: 404 Client Error for 
http+docker://localhost/v1.41/images/create?tag=formac&fromImage=lean-cli%2Fengi
ne: Not Found ("pull access denied for lean-cli/engine, repository does not 
exist or may require 'docker login': denied: requested access to the resource is
denied")`

Seems that the repository doesn't exist? not sure

**Comment by Martin-Molinero** [comment]
Hey @ben-green-kerro!
It seems a custom image has been built but is no longer available. `lean config list` will show that `engine-image` & `research-image` are set to `lean-cli/engine:latest` & `lean-cli/research:latest`. Running `lean config unset engine-image` & `lean config unset research-image` will make the lean cli go back to using the default images

**Comment by ben-green-kerro** [comment]
Thank's very much Martin. I don't remember making a custom image but that solved my issues perfectly :)
