### ISSUE TITLE
Offline Backtest Hangs on Initialization

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/lean-cli#165]
If we run `lean backtest <project-name>` without internet connection, Lean-CLI hangs when it tries to fetch the the modules json file on [lean/models/__init__.py#L27](https://github.com/QuantConnect/lean-cli/blob/master/lean/models/__init__.py#L27):

```python
res = requests.get(url)
```

Here is the stack from the forum thread "[Why is an internet connection required if running LEAN locally?](https://www.quantconnect.com/forum/discussion/14226/why-is-an-internet-connection-required-if-running-lean-locally/p1)"

```
lean backtest testProject1
^CTraceback (most recent call last):
 File "/home/user/lean-cli2/bin/lean", line 5, in <module>
   from lean.main import main
 File "/home/user/lean-cli2/lib/python3.8/site-packages/lean/main.py", line 95, in <module>
   from lean.commands import lean
 File "/home/user/lean-cli2/lib/python3.8/site-packages/lean/commands/__init__.py", line 17, in <module>
   from lean.commands.backtest import backtest
 File "/home/user/lean-cli2/lib/python3.8/site-packages/lean/commands/backtest.py", line 20, in <module>
   from lean.click import LeanCommand, PathParameter
 File "/home/user/lean-cli2/lib/python3.8/site-packages/lean/click.py", line 25, in <module>
   from lean.container import container
 File "/home/user/lean-cli2/lib/python3.8/site-packages/lean/container.py", line 17, in <module>
   from lean.components.api.api_client import APIClient
 File "/home/user/lean-cli2/lib/python3.8/site-packages/lean/components/api/api_client.py", line 23, in <module>
   from lean.components.api.account_client import AccountClient
 File "/home/user/lean-cli2/lib/python3.8/site-packages/lean/components/api/account_client.py", line 17, in <module>
   from lean.models.api import QCAccount
 File "/home/user/lean-cli2/lib/python3.8/site-packages/lean/models/__init__.py", line 27, in <module>
   res = requests.get(url)
 File "/home/user/lean-cli2/lib/python3.8/site-packages/requests/api.py", line 73, in get
   return request("get", url, params=params, **kwargs)
 File "/home/user/lean-cli2/lib/python3.8/site-packages/requests/api.py", line 59, in request
   return session.request(method=method, url=url, **kwargs)
 File "/home/user/lean-cli2/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
   resp = self.send(prep, **send_kwargs)
 File "/home/user/lean-cli2/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
   r = adapter.send(request, **kwargs)
 File "/home/user/lean-cli2/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
   resp = conn.urlopen(
 File "/home/user/lean-cli2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
   httplib_response = self._make_request(
 File "/home/user/lean-cli2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
   self._validate_conn(conn)
 File "/home/user/lean-cli2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
   conn.connect()
 File "/home/user/lean-cli2/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
   self.sock = conn = self._new_conn()
 File "/home/user/lean-cli2/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
   conn = connection.create_connection(
 File "/home/user/lean-cli2/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
   sock.connect(sa)
KeyboardInterrupt
```

We haven't been able to reproduce the issue. Apparently the request failed quickly and the exception held the connection error in our case. 

Possible solution:
Add [timeout](https://requests.readthedocs.io/en/latest/user/quickstart/#timeouts) parameter to `get` method call -- recommend by `requests` docs.
```python
res = requests.get(url, , timeout=1)   # times out after 1 second
```

**Comment by Martin-Molinero** [comment]
We should also improve the fetching of the modules json to update it once per day
