### ISSUE TITLE
Lean login command

### ISSUE THREAD

**Issue by martijnenco** [QuantConnect/lean-cli#23]
When I try to login with the credentials i got from the email and following the steps the login fails. I copy pasted the user id and the even first to notepad to make sure nu extra characters/markup is being copied.
Is this a bug?

#### Expected Behavior
It will log in

#### Actual Behavior
Throws the following error:
```sh
Error: Credentials are invalid
Visit https://www.lean.io/docs/lean-cli/tutorials/authentication#02-Logging-in for more information
```

#### Checklist
- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [X] I have provided detailed steps to reproduce the issue

**Comment by jmerle** [comment]
Can you please try it again with `lean login --verbose` and share the full output? Feel free to remove your user id and the masked API token if you'd like.

**Comment by martijnenco** [comment]
```bash
user@DESKTOP-1NFF5PV:~/Documents/Private/TDM500$ lean login --verbose
Your user id and API token are needed to make authenticated requests to the QuantConnect API
You can request these credentials on https://www.quantconnect.com/account
Both will be saved in /home/user/.lean/credentials
User id: 
API token: 
GET https://www.quantconnect.com/api/v2/projects/read with data {}
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/lean/main.py", line 96, in main
    lean.main(standalone_mode=False)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.6/site-packages/lean/click.py", line 83, in invoke
    result = super().invoke(ctx)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/lean/commands/login.py", line 50, in login
    "https://www.lean.io/docs/lean-cli/tutorials/authentication#02-Logging-in")
lean.models.errors.MoreInfoError: Credentials are invalid
Error: Credentials are invalid
Visit https://www.lean.io/docs/lean-cli/tutorials/authentication#02-Logging-in for more information
```

**Comment by jmerle** [comment]
Hmm, from those logs it does look like invalid credentials are the problem.

Because I have no idea what's wrong here I just released a new version of the CLI with more extensive debug logging around the "are the credentials valid" check. Can you try updating with `pip install --upgrade lean` and then post the full output of `lean login --verbose` again?

**Comment by martijnenco** [comment]
```
GET https://www.quantconnect.com/api/v2/projects/read with data {}
Request was not successful, status code 200, body:
{"errors":["Hash doesn't match. UID: <user_id> Hash: <hash> Timestamp: '1625580765'"],"success":false}
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/lean/components/api/api_client.py", line 96, in is_authenticated
    self.get("projects/read")
  File "/home/user/.local/lib/python3.6/site-packages/lean/components/api/api_client.py", line 75, in get
    return self._request("get", endpoint, {"params": parameters})
  File "/home/user/.local/lib/python3.6/site-packages/lean/components/api/api_client.py", line 137, in _request
    return self._parse_response(response)
  File "/home/user/.local/lib/python3.6/site-packages/lean/components/api/api_client.py", line 156, in _parse_response
    raise AuthenticationError()
lean.models.errors.AuthenticationError: Invalid credentials, please log in using `lean login`
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/lean/main.py", line 96, in main
    lean.main(standalone_mode=False)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.6/site-packages/lean/click.py", line 83, in invoke
    result = super().invoke(ctx)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/lean/commands/login.py", line 50, in login
    "https://www.lean.io/docs/lean-cli/tutorials/authentication#02-Logging-in")
lean.models.errors.MoreInfoError: Credentials are invalid
Error: Credentials are invalid
Visit https://www.lean.io/docs/lean-cli/tutorials/authentication#02-Logging-in for more information
```

I am in WSL2 on windows by the way.

**Comment by jmerle** [comment]
Thanks, no you can leave out your UUID and hash, the "Hash doesn't match" part of the message tells me enough. I'll do some debugging on WSL2 myself to see if there are problems with how the password is masked.

**Comment by martijnenco** [comment]
Alright, thank you for your effort so far :)
Does an test account/login exists to see if it is my environment?

**Comment by jmerle** [comment]
It's not just your environment, I also experience issues when I copy+paste my token into Windows Terminal + WSL2. Manually typing the password does seem to work here, but that's obviously not optimal. I've just released a new version of the CLI which disables password masking on WSL2, so if you run `pip install --upgrade lean` one more time you should be able to copy+paste your API token into `lean login`.

**Comment by martijnenco** [comment]
```bash
GET https://www.quantconnect.com/api/v2/projects/read with data {}
Successfully logged in
```
Thanks a lot!
I together with `wsl2` I use `Windows Terminal Preview`. Wouldn't have thought that that was the issue. I use this for my day to day work but never had any issues with it until now..

**Comment by jmerle** [comment]
Nice! Most of the CLI was tested on WSL2, but this password masking bug clearly slipped past. I just re-ran the end-to-end tests on WSL2 no other major features are broken, thanks for reporting the issue and for helping debug it!
