### ISSUE TITLE
`lean report` Targeting the Wrong File

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/lean-cli#256]
Create new project:
```
lean project-create --language python "Tes321"
```
Run backest:
```
lean backtest '.\Tes321\'
```
Genenate Report:
```
lean report
```

Output:
```
Generating a report from
'C:\Users\Alex\LeanCLI\Tes321\backtests\2022-12-16_15-06-21\data-monitor-report-20221216150638335.json'
20221216 15:07:14.789 TRACE:: QuantConnect.Report.Main(): Parsing source files...backtest-data-source-file.json,
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at QuantConnect.Report.NullResultValueTypeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object
existingValue, JsonSerializer serializer) in
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Report/NullResultValueTypeJsonConverter.cs:line 67
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter,
JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean
checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at QuantConnect.Report.Program.Main(String[] args) in
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Report/Program.cs:line 54
/lean-cli-start.sh: line 3:     7 Aborted                 dotnet QuantConnect.Report.dll
```

Note the target json file:
> data-monitor-report-20221216150638335.json

This file does have backtest result data

**Comment by jorgemanrubia** [comment]
I have the same problem. It seems it's missing a `Charts` property in the JSON as [per this line](https://github.com/QuantConnect/Lean/blob/master/Report/NullResultValueTypeJsonConverter.cs#L67). Adding: `"Charts": {}}` to the JSON prevents it from failing, but it generates an empty report for me.

**Comment by jorgemanrubia** [comment]
Oh, I think the problem is that it's mapping `backtest-data-source-file.json` to `data-monitor-report-123.json` instead of to the report itself `123.json`. When changing that manually it works for me:

```
    'mounts': [
        {'Target': '/Lean/Report/bin/Debug/config.json', 'Source': '/var/folders/1l/xrhg9vxd3llb760z5zhz8p6h0000gn/T/lean-cli-i_s9c74g/config.json', 'Type': 'bind', 'ReadOnly': True},
        {
            'Target': '/Lean/Report/bin/Debug/backtest-data-source-file.json',
            'Source': '/Users/jorge/Projects/lean/sandbox/backtests/2023-01-10_12-58-36/data-monitor-report-20230110115849819.json',
            'Type': 'bind',
            'ReadOnly': True
        },
```

**Comment by jorgemanrubia** [comment]
As a workaround, passing the specific json file works. E.g:

```
lean report --backtest-results backtests/2023-01-10_12-58-36/1423553480.json
```
