### ISSUE TITLE
lean cloud backtest error

### ISSUE THREAD

**Issue by ari62** [QuantConnect/lean-cli#280]
Hello,

When I run:
`lean cloud backtest "cleaned2" --verbose --push
`
I get the following. It doesn't say what is invalid about my file. I can upload the file in the Quantconnect website by right clicking and choosing upload. It seems to upload and run fine on the cloud through that method.

```
Request response: {"errors":["File content not valid. content: "],"success":false}
Request was not successful, status code 200, body:
{"errors":["File content not valid. content: "],"success":false}
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/statementParser/venv/lib/python3.8/site-packages/lean/components/cloud/push_manager.py", line 74, in push_projects
    self._push_project(path, organization_id)
  File "/Users/user/PycharmProjects/statementParser/venv/lib/python3.8/site-packages/lean/components/cloud/push_manager.py", line 149, in _push_project
    self._push_metadata(project_path, cloud_project)
  File "/Users/user/PycharmProjects/statementParser/venv/lib/python3.8/site-packages/lean/components/cloud/push_manager.py", line 223, in _push_metadata
    self._api_client.projects.update(cloud_project.projectId, **update_args)
  File "/Users/user/PycharmProjects/statementParser/venv/lib/python3.8/site-packages/lean/components/api/project_client.py", line 136, in update
    self._api.post("projects/update", request_parameters, data_as_json=False)
  File "/Users/user/PycharmProjects/statementParser/venv/lib/python3.8/site-packages/lean/components/api/api_client.py", line 95, in post
    return self._request("post", endpoint, options)
  File "/Users/user/PycharmProjects/statementParser/venv/lib/python3.8/site-packages/lean/components/api/api_client.py", line 158, in _request
    return self._parse_response(response)
  File "/Users/user/PycharmProjects/statementParser/venv/lib/python3.8/site-packages/lean/components/api/api_client.py", line 181, in _parse_response
    raise RequestFailedError(response, "\n".join(data["errors"]))
lean.models.errors.RequestFailedError: File content not valid. content:
Cannot push 'cleaned2': File content not valid. content: 
```

**Comment by jaredbroad** [comment]
Hi @ari62 - most likely a non UTF8 character that the CLI console couldn't display - guessing from a copy paste. Please attach the raw unmodified file for assistance.

**Comment by ari62** [comment]
@jaredbroad sorry im not sure which file is causing the issue, pls feel free to close this ticket if other people aren't experiencing the same issue.

**Comment by Martin-Molinero** [comment]
Closing for now, please feel free to reopen if you can reproduce, please share the projects content & the output of `>lean --version --verbose`, thank you!

**Comment by jmmaloney4** [comment]
For anyone finding this issue later, I had an empty file in my repo (an empty `.cs` file) that was causing this problem.
