### ISSUE TITLE
f"Something went wrong while pulling {image}, see the logs above for more information")

### ISSUE THREAD

**Issue by ArjunWhabi** [QuantConnect/lean-cli#29]
Hi All 

im getting the following error. Seems to be somthing with Docker and read write permissions

`PS D:\LeanCLI> lean backtest 'Crypto DonChan' --verbose
--> GET https://raw.githubusercontent.com/QuantConnect/lean-cli/master/announcements.json
Error response from daemon: error creating temporary lease: write /var/lib/desktop-containerd/daemon/io.containerd.metadata.v1.bolt/meta.db: read-only file system: unknown
Traceback (most recent call last):
  File "d:\python3.6.8\lib\site-packages\lean\main.py", line 96, in main
    lean.main(standalone_mode=False)
  File "d:\python3.6.8\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\python3.6.8\lib\site-packages\lean\click.py", line 114, in invoke
    result = super().invoke(ctx)
  File "d:\python3.6.8\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\python3.6.8\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\python3.6.8\lib\site-packages\lean\commands\backtest.py", line 342, in backtest
    docker_manager.pull_image(engine_image)
  File "d:\python3.6.8\lib\site-packages\lean\components\docker\docker_manager.py", line 70, in pull_image
    f"Something went wrong while pulling {image}, see the logs above for more information")
RuntimeError: Something went wrong while pulling quantconnect/lean:latest, see the logs above for more information
Error: Something went wrong while pulling quantconnect/lean:latest, see the logs above for more information`

**Comment by jmerle** [comment]
Hmm, I've never seen that error before, but going off of Google it seems like this is a disk space issue. Can you check whether you have ~20GB of free space to download the LEAN Docker images to?
