### ISSUE TITLE
1 validation error for QCProject liveResults

### ISSUE THREAD

**Issue by msbenjamin12** [QuantConnect/lean-cli#307]
Hi I keep getting an error when trying to push anything to the cloud. I receive the following error:

Cannot push 'project_name': 1 validation error for QCProject
liveResults
  none is not an allowed value (type=type_error.none.not_allowed)
  
**here is the full --verbose response:**

--> POST https://www.quantconnect.com/api/v2/projects/create with data:
{
    "name": "options_selection_test",
    "language": "Py",
    "organizationId": "xxxxxxxxxxxxxxxxxxxxxxxxxx"
}
Request response: {"projects":[{"projectId":14385875,"organizationId":"xxxxxxxxxxxxxxx","name":"options_selection_test 1","modified":"2023-03-21 
20:45:48","created":"2023-03-21 
20:45:48","ownerId":1234567,"language":"Py","collaborators":[{"id":0,"uid":226949,"blivecontrol":true,"epermission":"write","profileimage":"https:\/\/cdn.quantconnect.
com\/web\/i\/users\/profile\/default.jpg","email":"my_email@address.com","bio":null,"owner":true}],"leanVersionId":15298,"leanPinnedToMaster":true,"owner":true,"description":"","channelId":"P14385875-34527ef7d71f6496f793db8f63eeb
336","parameters":[],"liveResults":null,"libraries":[],"isAlphaStreamDeployment":0,"grid":null,"liveGrid":null,"builder":0,"paperEquity":null,"lastLiveDeployment":nul
l,"liveForm":null,"codeRunning":false,"leanEnvironment":1}],"success":true}
Traceback (most recent call last):
  File "/home/trader/quantconnect-ib/venv/lib/python3.10/site-packages/lean/components/cloud/push_manager.py", line 74, in push_projects
    self._push_project(path, organization_id)
  File "/home/trader/quantconnect-ib/venv/lib/python3.10/site-packages/lean/components/cloud/push_manager.py", line 132, in _push_project
    cloud_project = self._api_client.projects.create(project_name,
  File "/home/trader/quantconnect-ib/venv/lib/python3.10/site-packages/lean/components/api/project_client.py", line 75, in create
    return self._process_project(QCProject(**data["projects"][0]))
  File "/home/trader/quantconnect-ib/venv/lib/python3.10/site-packages/lean/models/pydantic.py", line 30, in __init__
    raise error
  File "/home/trader/quantconnect-ib/venv/lib/python3.10/site-packages/lean/models/pydantic.py", line 27, in __init__
    super().__init__(*args, **kwargs)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for QCProject
liveResults
  none is not an allowed value (type=type_error.none.not_allowed)
Cannot push 'options_selection_test': 1 validation error for QCProject
liveResults
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by Martin-Molinero** [comment]
Hey @msbenjamin12! Thanks for the report, fixed by https://github.com/QuantConnect/lean-cli/pull/306, will be released shortly
