### ISSUE TITLE
ERROR:: MarketHoursDatabaseJson.Convert():  System.ArgumentException

### ISSUE THREAD

**Issue by alphaDev23** [QuantConnect/lean-cli#400]
I'm receiving the following error with lean 1.0.177 when backtesting a project,

```
20240122 17:12:44.608 ERROR:: MarketHoursDatabaseJson.Convert():  System.ArgumentException: An item with the same key has already been added. Key: 7/3/2000 12:00:00 AM
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at QuantConnect.Util.LinqExtensions.ToDictionary[K,V](IEnumerable`1 enumerable) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Util/LinqExtensions.cs:line 38
   at QuantConnect.Util.MarketHoursDatabaseJsonConverter.MarketHoursDatabaseEntryJson.Convert(Entry underlyingEntry, Entry marketEntry) in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Util/MarketHoursDatabaseJsonConverter.cs:line 308
   at QuantConnect.Util.MarketHoursDatabaseJsonConverter.MarketHoursDatabaseJson.Convert() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Util/MarketHoursDatabaseJsonConverter.cs:line 102
```

**Comment by Martin-Molinero** [comment]
Hey @alphaDev23! Please pull the latest lean image, using `docker pull quantconnect/lean` or adding `--update` to the lean commands
