### ISSUE TITLE
Package QuantConnect.Brokerages.Binance 2.5.16814 is not compatible with net6.0 (.NETCoreApp,Version=v6.0).

### ISSUE THREAD

**Issue by lukaspistelak** [QuantConnect/lean-cli#528]
```
+ dotnet nuget add source /Modules
Package source with Name: Package source 1 added successfully.
+ mkdir /ModulesProject
+ dotnet new sln -o /ModulesProject
The template "Solution File" was created successfully.
+ dotnet new classlib -o /ModulesProject -f net6.0 --no-restore
The template "Class Library" was created successfully.
+ rm /ModulesProject/Class1.cs
+ rm -rf /root/.nuget/packages/quantconnect.brokerages.binance
+ dotnet add /ModulesProject package QuantConnect.Brokerages.Binance --version 2.5.16814
  Determining projects to restore...
  Writing /tmp/tmpBLpIeH.tmp
info : Adding PackageReference for package 'QuantConnect.Brokerages.Binance' into project '/ModulesProject/ModulesProject.csproj'.
info : Restoring packages for /ModulesProject/ModulesProject.csproj...
info : Installed QuantConnect.Brokerages.Binance 2.5.16814 from /Modules with content hash pbMFour5MhdMOB7q2yvM7aSazkyFA1HWUYJvtbm5r/gV2oZmClO+1JArsOA20GIVrX2fzA7j5NF/wWKk0rIocA==.
error: NU1202: Package QuantConnect.Brokerages.Binance 2.5.16814 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package QuantConnect.Brokerages.Binance 2.5.16814 supports: net9.0 (.NETCoreApp,Version=v9.0)
error: Package 'QuantConnect.Brokerages.Binance' is incompatible with 'all' frameworks in project '/ModulesProject/ModulesProject.csproj'.
Traceback (most recent call last):
  File "/root/.venv/lib/python3.12/site-packages/lean/main.py", line 94, in main
    lean.main(standalone_mode=False)
  File "/root/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.12/site-packages/lean/click.py", line 231, in invoke
    result = super().invoke(ctx)
             ^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.12/site-packages/lean/commands/live/deploy.py", line 352, in deploy
    lean_runner.run_lean(lean_config,
  File "/root/.venv/lib/python3.12/site-packages/lean/components/docker/lean_runner.py", line 174, in run_lean
    raise RuntimeError(
RuntimeError: Something went wrong while running 'test' in the 'lean-cli' environment, the output is stored in 'test/live/2024-12-19_20-33-01'
Error: Something went wrong while running 'test' in the 'lean-cli' environment, the output is stored in 'test/live/2024-12-19_20-33-01'

```

`lean live test/ --brokerage Binance --binance-exchange-name  Binance-USDM-Futures --data-provider-live Binance --verbose`

**Comment by Martin-Molinero** [comment]
Hey @lukaspistelak! Sorry for the inconvenience, we are releasing net9 support, please update to latest lean CLI version and lean image `--update`

**Comment by Martin-Molinero** [comment]
Please let us know if the issue persists though. Using `--no-update` will avoid the issue since lean cli 1.0.200 https://github.com/QuantConnect/lean-cli/releases/tag/1.0.200

**Comment by lukaspistelak** [comment]
> --update

i tried this: 

`lean live test/ --brokerage Binance --binance-exchange-name  Binance-USDM-Futures --data-provider-live Binance  --update`

```
20241220 09:59:48.141 ERROR:: Loader.TryCreatePythonAlgorithm():  System.Exception: AlgorithmPythonWrapper(): No module named 'binance'
  at <module>
    from binance.um_futures import UMFutures
 in broker_api.py: line 6
  at <module>
    from broker_api import API_binance
 in main.py: line 18
 No module named 'binance'
   at QuantConnect.AlgorithmFactory.Python.Wrappers.AlgorithmPythonWrapper..ctor(String moduleName) in AlgorithmFactory/Python/Wrappers/AlgorithmPythonWrapper.cs:line 182
   at QuantConnect.AlgorithmFactory.Loader.TryCreatePythonAlgorithm(String assemblyPath, IAlgorithm& algorithmInstance, String& errorMessage) in AlgorithmFactory/Loader.cs:line 173
20241220 09:59:48.143 ERROR:: Engine.Run():  QuantConnect.Lean.Engine.Setup.AlgorithmSetupException: During the algorithm initialization, the following exception has occurred: Loader.TryCreatePythonAlgorithm(): Unable to import python module 
/LeanCLI/main.py. AlgorithmPythonWrapper(): No module named 'binance'
  at <module>
    from binance.um_futures import UMFutures
 in broker_api.py: line 6
  at <module>
    from broker_api import API_binance
 in main.py: line 18
 No module named 'binance'
   at QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler.CreateAlgorithmInstance(AlgorithmNodePacket algorithmNodePacket, String assemblyPath) in Engine/Setup/BrokerageSetupHandler.cs:line 106
   at QuantConnect.Lean.Engine.Engine.Run(AlgorithmNodePacket job, AlgorithmManager manager, String assemblyPath, WorkerThread workerThread) in Engine/Engine.cs:line 116
20241220 09:59:48.146 TRACE:: JOB HANDLERS:
         DataFeed:             QuantConnect.Lean.Engine.DataFeeds.LiveTradingDataFeed
         Setup:                QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler
         RealTime:             QuantConnect.Lean.Engine.RealTime.LiveTradingRealTimeHandler
         Results:              QuantConnect.Lean.Engine.Results.LiveTradingResultHandler
         Transactions:         QuantConnect.Lean.Engine.TransactionHandlers.BrokerageTransactionHandler
         Object Store:         QuantConnect.Lean.Engine.Storage.LocalObjectStore
         History Provider:
         Brokerage:
         Data Provider:        QuantConnect.Lean.Engine.DataFeeds.DefaultDataProvider

20241220 09:59:48.150 ERROR:: Algorithm.Initialize() Error: During the algorithm initialization, the following exception has occurred: Loader.TryCreatePythonAlgorithm(): Unable to import python module /LeanCLI/main.py. AlgorithmPythonWrapper(): No module named 
'binance'
  at <module>
    from binance.um_futures import UMFutures
 in broker_api.py: line 6
  at <module>
    from broker_api import API_binance
 in main.py: line 18
 No module named 'binance' Stack Trace: During the algorithm initialization, the following exception has occurred: Loader.TryCreatePythonAlgorithm(): Unable to import python module /LeanCLI/main.py. AlgorithmPythonWrapper(): No module named 'binance'
  at <module>
    from binance.um_futures import UMFutures
 in broker_api.py: line 6
  at <module>
    from broker_api import API_binance
 in main.py: line 18
 No module named 'binance'
 During the algorithm initialization, the following exception has occurred: Loader.TryCreatePythonAlgorithm(): Unable to import python module /LeanCLI/main.py. AlgorithmPythonWrapper(): No module named 'binance'
  at <module>
    from binance.um_futures import UMFutures
 in broker_api.py: line 6
  at <module>
    from broker_api import API_binance
 in main.py: line 18
 No module named 'binance'

```
